# 初始化权限数据

resources:
  home:
    - id: 0
      server_name: "home"
      url: "/comments"
      method: "GET"
      version: "v1"
      description: "网站评论"

    - id: 1
      server_name: "home"
      url: "/friendslinks"
      method: "GET"
      version: "v1"
      description: "友链"

    - id: 2
      server_name: "home"
      url: "/updatelog"
      method: "GET"
      version: "v1"
      description: "更新日志"
  
  blogs:
    - id: 3
      server_name: "blogs"
      url: "/articles/<num:int>"
      method: "GET"
      version: "v2"
      description: "获取文章详情"    

    - id: 4
      server_name: "blogs"
      url: "/articles"
      method: "GET"
      version: "v2"
      description: "获取文章列表"   
    
    - id: 5
      server_name: "blogs"
      url: "/articles/update_status"
      method: "POST"
      version: "v2"
      description: "更新文章状态"   
    
    - id: 6
      server_name: "blogs"
      url: "/articles/search"
      method: "GET"
      version: "v2"
      description: "搜索文章"
    
    - id: 7
      server_name: "blogs"
      url: "/articles/count"
      method: "GET"
      version: "v2"
      description: "获取文章总数目"
    
    - id: 8
      server_name: "blogs"
      url: "/articlesTypes"
      method: "GET"
      version: "v2"
      description: "获取文章类型列表"
    
    - id: 9
      server_name: "blogs"
      url: "/articlesTags"
      method: "GET"
      version: "v2"
      description: "获取文章标签列表"


  drug:
    - id: 10
      server_name: "drug"
      url: "/words/random/"
      method: "GET"
      version: "v1"
      description: "随机获取一条毒鸡汤"

  fileBroker:
    - id: 11
      server_name: "fileBroker"
      url: "/"
      method: "POST"
      version: "v1"
      description: "文件预信息上传"

    - id: 12
      server_name: "fileBroker"
      url: "/search"
      method: "GET"
      version: "v1"
      description: "搜索文件上传的信息"
    
    - id: 13
      server_name: "fileBroker"
      url: "/"
      method: "GET"
      version: "v1"
      description: "下载文件"

  dataFaker:
    - id: 14
      server_name: "dataFaker"
      url: "/"
      method: "POST"
      version: "v1"
      description: "假数据生成预数据上传"
    
    - id: 15
      server_name: "dataFaker"
      url: "/search/"
      method: "GET"
      version: "v1"
      description: "根据生成嘛搜索生成的信息"

    - id: 16
      server_name: "dataFaker"
      url: "/"
      method: "GET"
      version: "v1"
      description: "根据下载码下载生成的假数据"

  shortUrl:
    - id: 17
      server_name: "shortUrl"
      url: "/create/"
      method: "POST"
      version: "v1"
      description: "生成短链接"

    - id: 18
      server_name: "shortUrl"
      url: "/redirect/"
      method: "GET"
      version: "v1"
      description: "访问短链接"
  
  apiCollector:
    - id: 19
      server_name: "apiCollector"
      url: "/task/"
      method: "POST"
      version: "v1"
      description: "启动爬取任务"

    - id: 20
      server_name: "apiCollector"
      url: "/task/"
      method: "GET"
      version: "v1"
      description: "获取爬取任务列表"
    
    - id: 21
      server_name: "apiCollector"
      url: "/apiInfo"
      method: "GET"
      version: "v1"
      description: "获取所有API信息"
    
    - id: 22
      server_name: "apiCollector"
      url: "/apiInfo/search"
      method: "GET"
      version: "v1"
      description: "获取指定API信息"

    - id: 23
      server_name: "apiCollector"
      url: "/apiResource/"
      method: "GET"
      version: "v1"
      description: "获取指定API资源"

    - id: 24
      server_name: "apiCollector"
      url: "/apiResource/"
      method: "POST"
      version: "v1"
      description: "创建一个API脚本"

# menus:
# - name: "首页"
#   url: "/home"
#   icon: "home"
#   children: []


roles:
  - id: 0
    name: "admin"
    description: "超级管理员"
    zone: "site"
  
  - id: 1
    name: "guest"
    description: "游客"
    zone: "site"
